name: "Proto- proto changes - NIX PR build"
on:
  pull_request:
    branches: 'main'
  workflow_dispatch:

jobs:
  lint-protos:
    name: lint-proto
    runs-on: ubuntu-22.04
    
    env:
      PROJECT_ID: 'mica-io-ops'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: cleanup old checkout  
        run: chmod +w -R ${GITHUB_WORKSPACE}; rm -rf ${GITHUB_WORKSPACE}/*;

      - uses: actions/checkout@v4

      - uses: workflow/nix-shell-action@v3
        with:
          script: |
            nix-shell --packages protobuf buf --run 'make lint'
